package com.wis.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-06T11:38:38.895+08:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "ScadaStationServiceService",
                  wsdlLocation = "http://portal.cdgas.com/QJYJWService/scadaService?wsdl",
                  targetNamespace = "http://scada.service.springjdbc.integration.qjyj.com/")
public class ScadaStationServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://scada.service.springjdbc.integration.qjyj.com/", "ScadaStationServiceService");
    public final static QName ScadaStationServicePort = new QName("http://scada.service.springjdbc.integration.qjyj.com/", "ScadaStationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://portal.cdgas.com/QJYJWService/scadaService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ScadaStationServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/文件/ideaProject/gas/src/main/java/com/wis/webservice/scadaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ScadaStationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ScadaStationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaStationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ScadaStationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ScadaStationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ScadaStationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ScadaDataService
     */
    @WebEndpoint(name = "ScadaStationServicePort")
    public ScadaDataService getScadaStationServicePort() {
        return super.getPort(ScadaStationServicePort, ScadaDataService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaDataService
     */
    @WebEndpoint(name = "ScadaStationServicePort")
    public ScadaDataService getScadaStationServicePort(WebServiceFeature... features) {
        return super.getPort(ScadaStationServicePort, ScadaDataService.class, features);
    }

}
