package com.wis.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-06T11:38:38.878+08:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://scada.ws.qjyj.com/", name = "ScadaDataService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ScadaDataService {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://scada.ws.qjyj.com/", partName = "return")
    public StationDTOArray findAllStationsData(

        @WebParam(partName = "domainId", name = "domainId")
        java.lang.String domainId
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://scada.ws.qjyj.com/", partName = "return")
    public StationDTO findStationDataBySid(

        @WebParam(partName = "domainId", name = "domainId")
        java.lang.String domainId,
        @WebParam(partName = "sId", name = "sId")
        long sId,
        @WebParam(partName = "isWlwan", name = "isWlwan")
        java.lang.String isWlwan
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://scada.ws.qjyj.com/", partName = "return")
    public StationDTOArray findStationDataBySids(

        @WebParam(partName = "domainId", name = "domainId")
        java.lang.String domainId,
        @WebParam(partName = "sIds", name = "sIds")
        java.lang.String sIds,
        @WebParam(partName = "isWlwan", name = "isWlwan")
        java.lang.String isWlwan
    );
}
