
package com.wis.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-06T11:38:38.792+08:00
 * Generated source version: 3.3.4
 *
 */
public final class ScadaDataService_ScadaStationServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://scada.service.springjdbc.integration.qjyj.com/", "ScadaStationServiceService");

    private ScadaDataService_ScadaStationServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ScadaStationServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ScadaStationServiceService ss = new ScadaStationServiceService(wsdlURL, SERVICE_NAME);
        ScadaDataService port = ss.getScadaStationServicePort();

        {
        System.out.println("Invoking findAllStationsData...");
        java.lang.String _findAllStationsData_domainId = "";
        com.wis.webservice.StationDTOArray _findAllStationsData__return = port.findAllStationsData(_findAllStationsData_domainId);
        System.out.println("findAllStationsData.result=" + _findAllStationsData__return);


        }
        {
        System.out.println("Invoking findStationDataBySid...");
        java.lang.String _findStationDataBySid_domainId = "";
        long _findStationDataBySid_sId = 0;
        java.lang.String _findStationDataBySid_isWlwan = "";
        com.wis.webservice.StationDTO _findStationDataBySid__return = port.findStationDataBySid(_findStationDataBySid_domainId, _findStationDataBySid_sId, _findStationDataBySid_isWlwan);
        System.out.println("findStationDataBySid.result=" + _findStationDataBySid__return);


        }
        {
        System.out.println("Invoking findStationDataBySids...");
        java.lang.String _findStationDataBySids_domainId = "";
        java.lang.String _findStationDataBySids_sIds = "";
        java.lang.String _findStationDataBySids_isWlwan = "";
        com.wis.webservice.StationDTOArray _findStationDataBySids__return = port.findStationDataBySids(_findStationDataBySids_domainId, _findStationDataBySids_sIds, _findStationDataBySids_isWlwan);
        System.out.println("findStationDataBySids.result=" + _findStationDataBySids__return);


        }

        System.exit(0);
    }

}
